# Generated by Django 4.1.6 on 2023-02-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[(None, 'Choose Category'), ('Buy', 'Property to buy'), ('Rent', 'Property to rent'), ('Sell', 'Property to sell'), ('Lease', 'Property to lease')], default=None, max_length=5),
        ),
    ]
